version: '1.0'

services:
  postgres:
    image: postgres:latest
    container_name: my_postgres_container
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    restart: on-failure             
    ports:
      - "${POSTGRES_PORT}:${POSTGRES_PORT}"               
    volumes:
      - postgres_data:/var/lib/postgresql/data
    env_file:
      - .env
  
  #backend:
  #  build: backend
  #  environment:
  #    DATABASE_URL: ${DATABASE_URL}
  #  depends_on:
  #    - postgres
  #  ports:
  #    - "${SERVER_PORT}:${SERVER_PORT}"
  #  env_file:
  #    - .env

volumes:
  postgres_data:
